[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Journalism: Exploring the Role of Intelligent Technologies in News Gathering and Reporting"
